---
- name: Install nfs utils
  yum:
    name: nfs-utils
    state: latest

- name: Create a mount directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /mnt/bigstorage/releases
    - /mnt/docker

- name: Create ext4 filesystem
  shell: mkfs.ext4 /dev/sdb

- name: Add mount entry in fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ item }}"
    create: yes
  with_items: 
    - 'cortx-storage.colo.seagate.com:/mnt/data1/releases/ /mnt/bigstorage/releases/    nfs    defaults    0 0'
    - '/dev/sdb                        /mnt/docker             ext4    defaults        1 1'  

- name: Mount filesystems available in fstab
  shell: mount -a
