---
- name: Install nfs utils
  yum:
    name: nfs-utils
    state: latest

- name: Create a mount directory if it does not exist
  file:
    path: /mnt/bigstorage
    state: directory
    mode: '0755'

- name: Add mount entry in fstab
  lineinfile:
    path: /etc/fstab
    line: cortx-storage.colo.seagate.com:/mnt/data1/releases/ /mnt/bigstorage/releases/    nfs    defaults    0 0
    create: yes

- name: Mount filesystems available in fstab
  shell: mount -a
