---
- name: Poweron the VM
  vmware_guest_powerstate:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    folder: "{{ vm_path }}"
    name: "{{ vm_name }}"
    validate_certs: no
    state: powered-on

- name: Install dependency packages
  yum:
    name:
      - python-pyvmomi
    state: present

- name: Revert VM to snapshot
  vmware_guest_snapshot:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    datacenter: "{{ vsphere_datacenter }}"
    folder: "{{ vm_path }}"
    name: "{{ vm_name }}"
    validate_certs: no
    state: revert
    snapshot_name: "{{ vm_snapshot_name }}"
