ORGANIZATION = "Seagate"

# MongoDB
MONGODB_DB_NAME = "jenkins"
MONGODB_JENKINS_JOBS_COLLECTION_NAME = "jenkins_jobs"
MONGODB_JENKINS_NODES_COLLECTION_NAME = "jenkins_nodes"
MONGODB_JENKINS_PLUGINS_COLLECTION_NAME = "jenkins_plugins"
MONGODB_JENKINS_BUILDS_COLLECTION_NAME = "jenkins_builds"

# Logstash
JENKINS_JOBS_INDEX_IDENTIFIER = "jenkins_jobs"
JENKINS_NODES_INDEX_IDENTIFIER = "jenkins_nodes"
JENKINS_PLUGINS_INDEX_IDENTIFIER = "jenkins_plugins"
JENKINS_BUILDS_INDEX_IDENTIFIER = "jenkins_builds"
