---

- name: "[deploy] : Deploy cluster on primary node"
  script: files/cortx_deploy.sh {{ BUILD_URL }} {{ NODE1 }} '{{ CLUSTER_PASS }}'
  ignore_errors: true

- name: "[validate] : Get installed rpm info"
  shell: yum list installed | grep 'cortx' 2>&1 | tee -a /root/installed_cortx_rpm_list.log
  ignore_errors: true

- name: "[validate] : Validate Deployment"
  script: files/validate_deployment.sh
  register: deployment_status_out
  failed_when: "\"Cortx Stack VM Deployment 'Success'\" not in deployment_status_out.stdout"

- pause:
    seconds: 20

- name: "[deploy] : Start cluster"
  command: cortx cluster start

# Wait for services to start
- name: "[validate] : Check cluster status"
  command: "hctl status"
  register: hctl_status
  until:
    - "'[started]  hax' in hctl_status.stdout"
    - "'[started]  confd' in hctl_status.stdout"
    - "'[started]  ioservice' in hctl_status.stdout"
    - "'[started]  s3server' in hctl_status.stdout"
  retries: 5
  delay: 30
  ignore_errors: true

- name: "[validate] : hctl status check"
  shell: hctl status 2>&1 | tee -a /root/hctl_status.log
  register: cluster_status
  ignore_errors: true

- name: "[validate] : Update Deployment status"
  shell: echo -e "Cortx Stack VM Deployment 'Failed' in hctl status check. \n \t {{ hctl_status.stdout }}" > /root/deployment_status.log
  when: "\"[started]  ioservice\" not in cluster_status.stdout"

- name: "[validate] : Validate Deployment - hctl status"
  fail: msg="Deployment failed. 'hctl status' returns unhealthy response"
  when: "\"[started]  ioservice\" not in cluster_status.stdout"

- name: "[validate] : Check service status"
  shell: "{{ item }} 2>&1 | tee -a /root/service_status.log"
  register: service_status
  with_items:
    - systemctl status rabbitmq-server
    - systemctl status elasticsearch
    - systemctl status haproxy
    - systemctl status s3authserver
    - systemctl status sspl-ll
    - systemctl status csm_agent
    - systemctl status csm_web
  ignore_errors: true
 