---

- name: "[deploy-prereq] : Download cortx-prereqs.sh script" 
  get_url:
    url: "{{ PREREQ_URL }}"
    dest: /root/cortx-prereqs.sh
    mode: '0755'
  delegate_to: "{{ item }}"
  with_items: "{{ groups['nodes'] }}"

- name: "[deploy-prereq] : Run cortx-prereqs.sh on primary node" 
  command: ./cortx-prereqs.sh --disable-sub-mgr -t {{ BUILD_URL }}
  ignore_errors: true
  become: true
  delegate_to: "srvnode-1"

- name: "[deploy-prereq] : Wait for nodes to reboot"
  wait_for:
      host={{ hostvars[item]['ansible_host'] }}
      port=22
      delay=30
      timeout=1800
  become: false
  ignore_errors: true
  with_items: "{{ groups['nodes'] }}"

- name: "[deploy-prereq] : Copy config file"
  template:
    src: config.ini.j2
    dest: /root/config.ini
    mode: '0754'
  delegate_to: "srvnode-1"

- name: "[deploy-prereq] : Install Git, Python3 on Primary Node"
  yum:
    name: [ 'git', 'python3', 'expect' ]
    state: latest
    update_cache: yes   
  delegate_to: "srvnode-1"