---

- name: "[deploy-prereq] : Copy config file"
  template:
    src: config.ini.j2
    dest: /root/config.ini
    mode: '0754'
  delegate_to: "srvnode-1"

- name: "[deploy-prereq] : Install Git, Python3 on Primary Node"
  yum:
    name: [ 'git', 'python3', 'expect' ]
    state: latest
    update_cache: yes   
  delegate_to: "srvnode-1"

# Install python pip package
- name: "[deploy-prereq] : Install python pip package"
  shell: pip3 install cryptography toml pyyaml
  delegate_to: "srvnode-1"