# Number of days of inactivity before an issue becomes stale
daysUntilStale: 7
# Number of days of inactivity before a stale issue is closed
daysUntilClose: false
# Issues with these labels will never be considered stale
exemptLabels:
  - improvement
  - "github actions"
# Label to use when marking an issue as stale
staleLabel: auto-stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue/pull request has been automatically marked as stale because it has not had
  recent activity. Tagging @shailesh-vaidya
# Comment to post when closing a stale issue. Set to `false` to disable
# closeComment: >
#  This issue/pull request has been automatically marked as closed because it has not had
#  recent activity.
