---
---
- name: Prepare Environment
  hosts: localhost
  become: true
  gather_facts: True
  roles:
    - role: 00_prepare_environment
      tags: ['00_PREP_ENV']

- name: Host Cleanup
  hosts: srvnode-1
  become: true
  vars_files: roles/host_cleanup/vars/config.yml 
  roles:
    - role: host_cleanup
