---

- name: Prepare Environment
  hosts: localhost
  become: true
  gather_facts: True
  roles:
    - role: 00_prepare_environment
    
- name: Deploy OpenLDAP
  hosts: srvnode-1
  become: true 
  roles:
    - role: openldap