---

- name: Prepare Environment
  hosts: localhost
  become: true
  gather_facts: True
  roles:
    - role: 00_prepare_environment
    
- name: Deploy Py utils
  hosts: srvnode-1
  become: true
  vars_files: roles/pyutils/vars/config.yml 
  roles:
    - role: pyutils
