---

- name: Prepare Environment
  hosts: localhost
  become: true
  gather_facts: True
  roles:
    - role: 00_prepare_environment
    
- name: Deploy SSPL
  hosts: srvnode-1
  become: true
  vars_files: roles/sspl/vars/config.yml 
  roles:
    - role: sspl