---
- name: "[install_cortx_manager] : Get Machine ID" 
  shell: cat /etc/machine-id
  register: machineid_out

- set_fact:
    MACHINE_ID: "{{ machineid_out.stdout }}"

- name: "[install_cortx_manager] : Get Secret Key" 
  shell: 'python3 -W"ignore" -c "from cortx.utils.security.cipher import Cipher; key = Cipher.generate_key('bae4b468-565d-49df-9495-a43a5d89babc','system');print(Cipher.encrypt(key, b'Seagate@1'))"'
  register: secretkey_out

- set_fact:
    SECRET_KEY: "{{ secretkey_out.stdout }}"

- name: "[install_cortx_manager] : Update post_install configuration template"
  ansible.builtin.replace:
    path: /opt/seagate/cortx/csm/conf/csm.post_install.tmpl.1-node
    regexp: 'TMPL_MACHINE_ID'
    replace: "{{ MACHINE_ID }}"

- name: "[install_cortx_manager] : Update prepare configuration template"
  ansible.builtin.replace:
    path: /opt/seagate/cortx/csm/conf/csm.prepare.tmpl.1-node
    regexp: "{{ item.tempval }}"
    replace: "{{ item.val }}"
  with_items:
    - { tempval: "TMPL_MACHINE_ID", val: "{{ MACHINE_ID }}" }
    - { tempval: "TMPL_SERVER_NAME", val: "{{ SERVER_NAME }}" }
    - { tempval: "TMPL_SERVER_HOSTNAME", val: "{{ ansible_nodename }}" }
    - { tempval: "TMPL_CLUSTER_ID", val: "{{ CLUSTER_ID }}" }
    - { tempval: "TMPL_CSM_SECRET_KEY", val: "{{ SECRET_KEY }}" }
    - { tempval: "TMPL_SGIAM_SECRET_KEY", val: "{{ SECRET_KEY }}" }  

- name: "[install_cortx_manager] : Update config configuration template"
  ansible.builtin.replace:
    path: /opt/seagate/cortx/csm/conf/csm.config.tmpl.1-node
    regexp: "{{ item.tempval }}"
    replace: "{{ item.val }}"
  with_items:  
    - { tempval: "TMPL_MACHINE_ID", val: "{{ MACHINE_ID }}" }
    - { tempval: "TMPL_SERVER_NAME", val: "{{ SERVER_NAME }}" }
    - { tempval: "TMPL_SERVER_HOSTNAME", val: "{{ ansible_nodename }}" }
    - { tempval: "TMPL_CLUSTER_ID", val: "{{ CLUSTER_ID }}" }
    - { tempval: "TMPL_CSM_SECRET_KEY", val: "{{ SECRET_KEY }}" }
    - { tempval: "TMPL_SGIAM_SECRET_KEY", val: "{{ SECRET_KEY }}" }  

- name: "[install_cortx_manager] : Update init configuration template"
  ansible.builtin.replace:
    path: /opt/seagate/cortx/csm/conf/csm.init.tmpl.1-node
    regexp: "{{ item.tempval }}"
    replace: "{{ item.val }}"
  with_items:
    - { tempval: "TMPL_MACHINE_ID", val: "{{ MACHINE_ID }}" }
    - { tempval: "TMPL_SERVER_NAME", val: "{{ SERVER_NAME }}" }
    - { tempval: "TMPL_SERVER_HOSTNAME", val: "{{ ansible_nodename }}" }
    - { tempval: "TMPL_CLUSTER_ID", val: "{{ CLUSTER_ID }}" }
    - { tempval: "TMPL_CSM_SECRET_KEY", val: "{{ SECRET_KEY }}" }
    - { tempval: "TMPL_SGIAM_SECRET_KEY", val: "{{ SECRET_KEY }}" }

- name: Display post_install contents
  command: cat /opt/seagate/cortx/csm/conf/csm.post_install.tmpl.1-node
  register: post_install_output

- name: Print to console
  debug: msg = "{{ post_install_output.stdout }}"

- name: Display prepare contents
  command: cat /opt/seagate/cortx/csm/conf/csm.prepare.tmpl.1-node
  register: prepare_output

- name: Print to console
  debug: msg = "{{ prepare_output.stdout }}"