---
- name: "[mini_provisioning] : CSM Post Install" 
  shell: "{{ item }}" 
  with_items:
    - "/opt/seagate/cortx/utils/bin/utils_setup post_install --config json:///opt/seagate/cortx/utils/conf/utils.post_install.tmpl.1-node"
    - "/opt/seagate/cortx/csm/bin/csm_setup post_install --config json:///opt/seagate/cortx/csm/conf/csm.post_install.tmpl.1-node"
  
- name: "[mini_provisioning] : CSM Prepare"
  shell: /opt/seagate/cortx/csm/bin/csm_setup prepare --config json:///opt/seagate/cortx/csm/conf/csm.prepare.tmpl.1-node
  
- name: "[mini_provisioning] : CSM Config" 
  shell: "{{ item }}"
  with_items:
    - "/opt/seagate/cortx/utils/bin/utils_setup config --config json:///opt/seagate/cortx/utils/conf/utils.config.tmpl.1-node"
    - "/opt/seagate/cortx/csm/bin/csm_setup config --config json:///opt/seagate/cortx/csm/conf/csm.config.tmpl.1-node"

- name: "[mini_provisioning] : CSM Init" 
  shell: /opt/seagate/cortx/csm/bin/csm_setup init --config json:///opt/seagate/cortx/csm/conf/csm.init.tmpl.1-node
  
- name: "[mini_provisioning] : Enable csm_agent"
  shell: systemctl enable csm_agent

- name: "[mini_provisioning] : Start csm_agent"
  shell: systemctl start csm_agent
  register: csm_agent_out
  ignore_errors: true

- name: "[mini_provisioning] : Journalctl log" 
  shell: journalctl --unit=csm_agent.service | tail -n 100
  when: csm_agent_out.rc != 0

- name: "[mini_provisioning] : Run Sanity Test"
  shell: csm_setup test -t /opt/seagate/cortx/csm/test/plans/self_test.pln -f /opt/seagate/cortx/csm/test/test_data/args.yaml -l /tmp/csm_test -o /tmp/test.out
  register: csm_test_out
  failed_when: '"PASS" not in csm_test_out.stdout'