# #######################################################################################
# Description:
#-------------
#         This tasks configure and initializes the Hare 
# Reference:
#----------- 
#         https://github.com/Seagate/cortx-Hare/wiki/Hare-deployment-using-Hare_setup-on-singlenode-VM
# Steps:
#--------
#      1. Execute Hare:post_install      
#      2. Execute Hare:config
#      3. Execute Hare:init  
#      2. Execute Hare:test  
##########################################################################################

# Get Hostname
- name: "[mini_provisioning] : Get Hostname" 
  shell: hostname
  register: hostname_out

# Get Machine ID
- name: "[mini_provisioning] : Get Machine ID" 
  shell: cat /etc/machine-id
  register: machineid_out

# Get IP Address
- name: "[mini_provisioning] : Get Ipaddress" 
  shell: hostname -I | cut -d' ' -f2 | xargs
  register: ipaddress_out

- set_fact:
    HOSTNAME: "{{ hostname_out.stdout }}"
    MACHINE_ID: "{{ machineid_out.stdout }}"
    IP_ADDRESS: "{{ ipaddress_out.stdout }}"

# Create confstore.json in deployment node
- name: "[mini_provisioning] : Copy confstore json file"
  template:
    src: confstore.json.j2
    dest: /root/confstore.json

# Execute Hare:Post_Install
- name: "[mini_provisioning] : Post Install" 
  shell: /opt/seagate/cortx/hare/bin/hare_setup --post_install

# Execute Hare:Config
- name: "[mini_provisioning] : Hare Config" 
  shell: /opt/seagate/cortx/hare/bin/hare_setup --config 'json:///root/confstore.json' --filename '/var/lib/hare/cluster.yaml'

# Execute Hare:Init
- name: "[mini_provisioning] : Hare Init" 
  shell: /opt/seagate/cortx/hare/bin/hare_setup --init

# Execute Hare:Test
- name: "[mini_provisioning] : Hare Test" 
  shell: /opt/seagate/cortx/hare/bin/hare_setup --test