---
SERVER_NAME: "srvnode-1"
CLUSTER_ID: "bae4b468-565d-49df-9495-a43a5d89babc"
SECRET_KEY: "gAAAAABgZF7KOL5wqOwt_VpJ0B0tXHlsbfARqKldkiVtOeGpEjBq_Ws38qHHAo27zCPIKGSaXqSAgGXTzFJMZRTrXWWn6Pivsg=="


REQUIRED_VARS:
  - NODE1
  - CORTX_BUILD

