---

- name: "[prepare] : Validate the required input arguments for this playbook"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"

- name: "[ Prepare ] : Generate host file"
  template:
    src: hosts_srvnodes.j2
    dest: inventories/factory_deployment/hosts_srvnodes
    mode: '0754'

- meta: refresh_inventory

- include: passwordless_authentication.yml

- name: "[deploy-prep] : Wait for SSH Connection"
  pause:
    minutes: 3



