---

- name: "[prepare] : Validate the required input arguments for this playbook"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"
  

#- debug: msg="{{lookup('file', 'inventories/factory_deployment/{{CONFIG_NAME}}') }}" 

#  get_url:
#    url:  '{{CONFIG}}'
#    dest: inventories/factory_deployment/
#    mode: '0754'
    
- name: "[ Prepare ] : Generate host file"
  template:
    src: hosts_srvnodes.j2
    dest: inventories/factory_deployment/hosts_srvnodes
    mode: '0754'

- meta: refresh_inventory

- include: passwordless_authentication.yml

- name: "[deploy-prep] : Wait for SSH Connection"
  pause:
    minutes: 1

- name: show templating results
  debug:
    msg: "{{ lookup('template', './hosts_srvnodes.j2') }}"    

- name: Display hostname of srvnode1
  shell: echo `hostname`
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
  register: host_op
  
- debug: var=host_op

