---

- name: "[prepare] : Validate the required input arguments for this playbook"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"

- vars:
    url: "{{CONFIG_URL}}"
    file_name: "{{ url | basename }}"

- debug: var=file_name

- name: Download config file
  get_url:
    url: "{{CONFIG_URL}}"
    dest: /root
    

#- shell: cat my.yaml
#  register: result
      
#- set_fact:
#  myvar: "{{ result.stdout | from_yaml | to_json }}"

#- copy:
#    content: "{{ myvar }}"
#    dest:    my.json
        
- name: "[ Prepare ] : Generate host file"
  template:
    src: hosts_srvnodes.j2
    dest: inventories/factory_deployment/hosts_srvnodes
    mode: '0754'

- meta: refresh_inventory


- name: show templating results
  debug:
    msg: "{{ lookup('template', './hosts_srvnodes.j2') }}"    
    
- include: passwordless_authentication.yml

- name: "[deploy-prep] : Wait for SSH Connection"
  pause:
    minutes: 1

- name: show templating results
  debug:
    msg: "{{ lookup('template', './hosts_srvnodes.j2') }}"    

- name: Display hostname of srvnode1
  shell: echo `hostname`
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
  register: host_op
  
- debug: var=host_op

