---

- name: "[prepare] : Validate the required input arguments for this playbook"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"

- name: "[ Prepare ] : Generate host file"
  template:
    src: hosts_srvnodes.j2
    dest: inventories/hw_deployment/hosts_srvnodes
    mode: '0754'

- meta: refresh_inventory

- name: show templating results
  debug:
    msg: "{{ lookup('template', './hosts_srvnodes.j2') }}"

- meta: refresh_inventory

- name: Display hostname of srvnode1
  shell: echo `hostname`
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

#- include: passwordless_authentication.yml

#- name: "[deploy-prep] : Wait for SSH Connection"
#  pause:
#    minutes: 1
#- name: Install device-mapper-multipath
#  shell: yum install -y device-mapper-multipath
#  delegate_to: "{{ item }}"
#  with_items: "{{ groups['srvnodes'] }}" 
    
#- name: Copy multipath configuration
#  shell: cp /usr/share/doc/device-mapper-multipath-0.4.9/multipath.conf /etc/multipath.conf
#  delegate_to: "{{ item }}"
#  with_items: "{{ groups['srvnodes'] }}" 
 
#- name: Restart multipath service
#  shell: systemctl restart multipathd
#  delegate_to: "{{ item }}"
#  with_items: "{{ groups['srvnodes'] }}" 
