---

- name: "[prepare] : Validate the required input arguments for this playbook"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"

#- set_fact:
#    file_name: "{{ CONFIG_URL | basename }}"

- name: Download config file
  get_url:
    url: "{{CONFIG_URL}}"
    dest: inventories/factory_deployment/hosts_srvnodes
    
#- shell: cat "/root/{{file_name}}"
#  register: result
      
#- set_fact:
#    myvar: "{{ result.stdout | from_yaml | to_json }}"

#- copy:
#    content: "{{ myvar }}"
#    dest:    my.json
        
#- name: "[ Prepare ] : Generate host file"
#  template:
#    src: hosts_srvnodes.j2
#    dest: inventories/factory_deployment/hosts_srvnodes
#    mode: '0754'

- meta: refresh_inventory


#- name: show templating results
#  debug:
#    msg: "{{ lookup('template', './hosts_srvnodes.j2') }}"    
    
- include: passwordless_authentication.yml

#- name: "[deploy-prep] : Wait for SSH Connection"
#  pause:
#    minutes: 1

#- name: show templating results
#  debug:
#    msg: "{{ lookup('template', './hosts_srvnodes.j2') }}"    

- name: BMC IP for all nodes
  shell: ipmitool lan print 1 | grep  'IP Address' | grep -oE '([0-9]{1,3}.){3}[0-9]{1,3}' | sed -n '1p'
  register: bmc_ip_add
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
  
- debug: var="{{item}}"
  with_items: "{{bmc_ip_add.results|map(attribute='stdout_lines')|list}}


