---

- name: "[prepare] : Validate the required input arguments for this playbook"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"

- name: "[ Prepare ] : Generate host file"
  template:
    src: hosts_srvnodes.j2
    dest: inventories/factory_deployment/hosts_srvnodes
    mode: '0754'

- meta: refresh_inventory

- name: "[prepare] : Refreshing 'known hosts'"
  command: echo "{{ hostvars[item]['ansible_default_ipv6']['address'] }}"
  with_items: "{{ groups['srvnodes'] }}"
  register: op_hosts
 
- debug: var=op_hosts


#- include: passwordless_authentication.yml

#- name: "[deploy-prep] : Wait for SSH Connection"
#  pause:
#    minutes: 1
    
#- name: "Display hostname"
 # shell: echo `hostname`



