---
- name: Create cortx directory
  shell: mkdir /mnt/cortx
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: Download cortx_prep
  shell: (cd /mnt/cortx && curl -O https://raw.githubusercontent.com/Seagate/cortx-prvsnr/pre-cortx-1.0/srv/components/provisioner/scripts/cortx_prep.sh)
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: Changing perm of "/mnt/cortx/cortx_prep.sh", adding "+x"
  file: dest=/mnt/cortx/cortx_prep.sh mode=a+x
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: Prepare setup
  shell: /mnt/cortx/cortx_prep.sh -t {{ CORTX_BUILD_URL }}
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
