---
- name: Install device-mapper-multipath
  shell: yum install -y device-mapper-multipath
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
    
- name: Copy multipath configuration
  shell: cp /usr/share/doc/device-mapper-multipath-0.4.9/multipath.conf /etc/multipath.conf
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
 
- name: Restart multipath service
  shell: systemctl restart multipathd
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
    
- name: Display hostname
  shell: echo `hostname`
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
 
- name: Create cortx directory
  shell: rm -rf /mnt/cortx
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: Create cortx directory
  shell: mkdir /mnt/cortx
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: Download cortx_prep
  shell: (cd /mnt/cortx && curl -O https://raw.githubusercontent.com/gauravchaudhari02/config-store/main/cortx-prep.sh)
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}"

- name: Changing perm of "/mnt/cortx/cortx-prep.sh", adding "+x"
  file: dest=/mnt/cortx/cortx-prep.sh mode=a+x
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: Prepare setup
  shell: /mnt/cortx/cortx-prep.sh -t {{ CORTX_BUILD_URL }}
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
