---

- name: Install device-mapper-multipath
  shell: yum install -y device-mapper-multipath
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
    
- name: Copy multipath configuration
  shell: cp /usr/share/doc/device-mapper-multipath-0.4.9/multipath.conf /etc/multipath.conf
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
 
- name: Restart multipath service
  shell: systemctl restart multipathd
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
  
- name: "Server Configuration srvnode-1"
  command: cortx_setup server config --name srvnode-1 --type HW
  delegate_to: "srvnode-1"  

- name: "Server Configuration srvnode-2"
  command: cortx_setup server config --name srvnode-2 --type HW
  delegate_to: "srvnode-2"

- name: "Server Configuration srvnode-3"
  command: cortx_setup server config --name srvnode-3 --type HW
  delegate_to: "srvnode-3"

- name: "Network Configuration lnet"
  command: cortx_setup network config --transport lnet --mode tcp
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Network Configuration eno1"
  command: cortx_setup network config --interfaces eno1 --type management
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Network Configuration data"
  command: cortx_setup network config --interfaces enp175s0f0 --type data
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Network Configuration private"
  command: cortx_setup network config --interfaces enp216s0f0 --type private
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Network Configuration bmc"
  command: cortx_setup network config --bmc 10.237.66.164 --user bmcadmin --password adminBMC!
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Storage Configuration gallium primary"
  command: cortx_setup storage config --controller gallium --mode primary --ip 10.0.0.2 --port 80 --user manage --password Seagate123$
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Storage Configuration gallium secondary"
  command: cortx_setup storage config --controller gallium --mode secondary --ip 10.0.0.3 --port 80 --user manage --password Seagate123$
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Storage Configuration enclosure-1"
  command: cortx_setup storage config --name enclosure-1 --type RBOD
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
  
- name: "cvg0 data device list"
  script: files/cvg0_datalist.py
  register: cvg0_data_list
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- set_fact:
    cvg0_data: "{{cvg0_data_list.stdout}}"
    
- debug: var=cvg0_data

- name: "cvg0 meta device list"
  script: files/cvg0_metalist.py
  register: cvg0_meta_list
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
  
- set_fact:
    cvg0_meta: "{{cvg0_meta_list.stdout }}"
 
- debug: var=cvg0_meta

- name: "cvg1 data device list"
  script: files/cvg1_datalist.py
  register: cvg1_data_list
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
  
- set_fact:
    cvg1_data: "{{cvg1_data_list.stdout}}"
 
- debug: var=cvg1_data

- name: "cvg1 meta device list"
  script: files/cvg1_metalist.py
  register: cvg1_meta_list
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
 
- set_fact:
    cvg1_meta: "{{cvg1_meta_list.stdout}}"
  
- debug: var=cvg1_meta

#- name: "Storage Configuration cvg 0 data_devices"
#  command: cortx_setup storage config --cvg 0 --data_devices /dev/disk/by-id/dm-name-mpathc,/dev/disk/by-id/dm-name-mpathd,/dev/disk/by-id/dm-name-mpathe,/dev/disk/by-id/dm-name-mpathf,/dev/disk/by-id/dm-name-mpathg,/dev/disk/by-id/dm-name-mpathh,/dev/disk/by-id/dm-name-mpathi,/dev/disk/by-id/dm-name-mpathj,/dev/disk/by-id/dm-name-mpathk --metadata_devices /dev/disk/by-id/dm-name-mpathb
#  delegate_to: "{{ item }}"
#  with_items: "{{ groups['srvnodes'] }}" 
  
#- name: "Storage Configuration cvg 1 data_devices"
#  command: cortx_setup storage config --cvg 1 --data_devices /dev/disk/by-id/dm-name-mpatha,/dev/disk/by-id/dm-name-mpathl,/dev/disk/by-id/dm-name-mpathn,/dev/disk/by-id/dm-name-mpatho,/dev/disk/by-id/dm-name-mpathp,/dev/disk/by-id/dm-name-mpathq,/dev/disk/by-id/dm-name-mpathr,/dev/disk/by-id/dm-name-mpaths,/dev/disk/by-id/dm-name-mpatht  --metadata_devices /dev/disk/by-id/dm-name-mpathm
#  delegate_to: "{{ item }}"
#  with_items: "{{ groups['srvnodes'] }}" 
