---

- name: Install device-mapper-multipath
  shell: yum install -y device-mapper-multipath
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
    
- name: Copy multipath configuration
  shell: cp /usr/share/doc/device-mapper-multipath-0.4.9/multipath.conf /etc/multipath.conf
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
 
- name: Restart multipath service
  shell: systemctl restart multipathd
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
  
- name: "Server Configuration srvnode-1"
  command: cortx_setup server config --name srvnode-1 --type HW
  delegate_to: "srvnode-1"  

- name: "Server Configuration srvnode-2"
  command: cortx_setup server config --name srvnode-2 --type HW
  delegate_to: "srvnode-2"

- name: "Server Configuration srvnode-3"
  command: cortx_setup server config --name srvnode-3 --type HW
  delegate_to: "srvnode-3"

- name: "Network Configuration lnet"
  command: cortx_setup network config --transport lnet --mode tcp
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Network Configuration eno1"
  command: cortx_setup network config --interfaces eno1 --type management
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Network Configuration data"
  command: cortx_setup network config --interfaces "{{DATA_INTERFACE}}" --type data
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Network Configuration private"
  command: cortx_setup network config --interfaces "{{PRIVATE_INTERFACE}}" --type private
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Network Configuration bmc srvnode-1"
  command: cortx_setup network config --bmc "{{BMC_IP_PRIMARY}}" --user bmcadmin --password adminBMC!
  delegate_to: "srvnode-1" 
  
- name: "Network Configuration bmc srvnode-2"
  command: cortx_setup network config --bmc "{{BMC_IP_SECONDARY1}}" --user bmcadmin --password adminBMC!
  delegate_to: "srvnode-2" 
  
- name: "Network Configuration bmc srvnode-3"
  command: cortx_setup network config --bmc "{{BMC_IP_SECONDARY2}}" --user bmcadmin --password adminBMC!
  delegate_to: "srvnode-3" 

- name: "Storage Configuration gallium primary"
  command: cortx_setup storage config --controller gallium --mode primary --ip 10.0.0.2 --port 80 --user manage --password Seagate123$
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Storage Configuration gallium secondary"
  command: cortx_setup storage config --controller gallium --mode secondary --ip 10.0.0.3 --port 80 --user manage --password Seagate123$
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: "Storage Configuration enclosure-1"
  command: cortx_setup storage config --name enclosure-1 --type RBOD
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

  #cvg0 and cvg1 srvnode-1
- name: "cvg0 data device list"
  script: files/cvg0_datalist.py
  register: cvg0_data_list_node1
  delegate_to: "srvnode-1" 
  
- debug: var=cvg0_data_list_node1

- set_fact:
    cvg0_data_node1: "{{ item }}"
  with_items: "{{ cvg0_data_list_node1.stdout_lines }}"
 
- debug: var=cvg0_data_node1

- debug: var=item
  with_items: "{{ cvg0_data_list_node1.stdout_lines }}"
  
- name: "cvg0 meta device list"
  script: files/cvg0_metalist.py
  register: cvg0_meta_list_node1
  delegate_to: "srvnode-1" 
  
- set_fact:
    cvg0_meta_node1: "{{ item }}"
  with_items: "{{ cvg0_meta_list_node1.stdout_lines }}"
  
- debug: var=cvg0_meta_node1

- debug: var=item
  with_items: "{{ cvg0_meta_list_node1.stdout_lines }}"

- name: "cvg1 data device list"
  script: files/cvg1_datalist.py
  register: cvg1_data_list_node1
  delegate_to: "srvnode-1"
  
- set_fact:
    cvg1_data_node1: "{{ item }}"
  with_items: " {{ cvg1_data_list_node1.stdout_lines }} "  

- debug: var=cvg1_data_node1

- debug: var=item
  with_items: "{{ cvg1_data_list_node1.stdout_lines }}"
 
- name: "cvg1 meta device list"
  script: files/cvg1_metalist.py
  register: cvg1_meta_list_node1
  delegate_to: "srvnode-1"
 
- set_fact:
    cvg1_meta_node1: "{{ item }}" 
  with_items: "{{ cvg1_meta_list_node1.stdout_lines }}"

- debug: var=cvg1_meta_node1

- debug: var=item
  with_items: "{{ cvg1_meta_list_node1.stdout_lines }}"

#cvg0 and cvg1 srvnode-2
- name: "cvg0 data device list"
  script: files/cvg0_datalist.py
  register: cvg0_data_list_node2
  delegate_to: "srvnode-2" 

- set_fact:
    cvg0_data_node2: "{{ item }}"
  with_items: "{{ cvg0_data_list_node2.stdout_lines }}"

- debug: var=cvg0_data_node2

- debug: var=item
  with_items: "{{ cvg0_data_list_node2.stdout_lines }}"


- name: "cvg0 meta device list"
  script: files/cvg0_metalist.py
  register: cvg0_meta_list_node2
  delegate_to: "srvnode-2" 
  
- set_fact:
    cvg0_meta_node2: "{{ item }}"
  with_items: "{{ cvg0_meta_list_node2.stdout_lines }}"
 
- debug: var=cvg0_meta_node2

- debug: var=item
  with_items: "{{ cvg0_meta_list_node2.stdout_lines }}"

- name: "cvg1 data device list"
  script: files/cvg1_datalist.py
  register: cvg1_data_list_node2
  delegate_to: "srvnode-2"
  
- set_fact:
    cvg1_data_node2: "{{ item }}"
  with_items: "{{ cvg1_data_list_node2.stdout_lines }}"
  
- debug: var=cvg1_data_node2

- debug: var=item
  with_items: "{{ cvg1_data_list_node2.stdout_lines }}"

- name: "cvg1 meta device list"
  script: files/cvg1_metalist.py
  register: cvg1_meta_list_node2
  delegate_to: "srvnode-2"
 
- set_fact:
    cvg1_meta_node2: "{{ item }}"
  with_items: "{{ cvg1_meta_list_node2.stdout_lines }}"
  
- debug: var=cvg1_meta_node2

- debug: var=item
  with_items: "{{ cvg1_meta_list_node2.stdout_lines }}"
  
#cvg0 and cvg1 srvnode-3
- name: "cvg0 data device list"
  script: files/cvg0_datalist.py
  register: cvg0_data_list_node3
  delegate_to: "srvnode-3" 

- set_fact:
    cvg0_data_node3: "{{ item }}"
  with_items: "{{ cvg0_data_list_node3.stdout_lines }}"
  
- debug: var=cvg0_data_node3

- debug: var=item
  with_items: "{{ cvg0_data_list_node3.stdout_lines }}"
  

- name: "cvg0 meta device list"
  script: files/cvg0_metalist.py
  register: cvg0_meta_list_node3
  delegate_to: "srvnode-3" 
  
- set_fact:
    cvg0_meta_node3: "{{ item }}"
  with_items: "{{ cvg0_meta_list_node3.stdout_lines }}"
  
- debug: var=cvg0_meta_node3

- debug: var=item
  with_items: "{{ cvg0_meta_list_node3.stdout_lines }}"

- name: "cvg1 data device list"
  script: files/cvg1_datalist.py
  register: cvg1_data_list_node3
  delegate_to: "srvnode-3"
  
- set_fact:
    cvg1_data_node3: "{{ item }}"
  with_items: "{{ cvg1_data_list_node3.stdout_lines }}"
  
- debug: var=cvg1_data_node3

- debug: var=item
  with_items: "{{ cvg1_data_list_node3.stdout_lines }}"


- name: "cvg1 meta device list"
  script: files/cvg1_metalist.py
  register: cvg1_meta_list_node3
  delegate_to: "srvnode-3"
 
- set_fact:
    cvg1_meta_node3: "{{ item }}"
  with_items: "{{ cvg1_meta_list_node3.stdout_lines }}"
  
- debug: var=cvg1_meta_node3

- debug: var=item
  with_items: "{{ cvg1_meta_list_node3.stdout_lines }}"

# cvg0 and cvg1 storage config on srvnode-1
- name: "Storage Configuration cvg 0 data_devices on srvnode-1"
  command: cortx_setup storage config --cvg dg01 --data-devices "{{ cvg0_data_node1 }}" --metadata-devices "{{ cvg0_meta_node1 }}"
  delegate_to: "srvnode-1"
  
- name: "Storage Configuration cvg 1 data_devices on srvnode-1 "
  command: cortx_setup storage config --cvg dg02 --data-devices "{{ cvg1_data_node1 }}" --metadata-devices "{{ cvg1_meta_node1 }}"
  delegate_to: "srvnode-1"
  
# cvg0 and cvg1 storage config on srvnode-2
- name: "Storage Configuration cvg 0 data_devices on srvnode-2"
  command: cortx_setup storage config --cvg dg01 --data-devices "{{ cvg0_data_node2 }}" --metadata-devices "{{ cvg0_meta_node2 }}"
  delegate_to: "srvnode-2"

- name: "Storage Configuration cvg 1 data_devices on srvnode-2 "
  command: cortx_setup storage config --cvg dg02 --data-devices "{{ cvg1_data_node2 }}" --metadata-devices "{{ cvg1_meta_node2 }}"
  delegate_to: "srvnode-2"

# cvg0 storage config on srvnode-3
- name: "Storage Configuration cvg 0 data_devices on srvnode-3"
  command: cortx_setup storage config --cvg dg01 --data-devices "{{ cvg0_data_node3 }}" --metadata-devices "{{ cvg0_meta_node3 }}"
  delegate_to: "srvnode-3"
  
- name: "Storage Configuration cvg 1 data_devices on srvnode-3 "
  command: cortx_setup storage config --cvg dg02 --data-devices "{{ cvg1_data_node3 }}" --metadata-devices "{{ cvg1_meta_node3 }}"
  delegate_to: "srvnode-3"



