---

- meta: refresh_inventory

- name: Install security certificate
  command: cortx_setup security config --certificate /opt/seagate/cortx/provisioner/srv/components/misc_pkgs/ssl_certs/files/stx.pem

#- name: Configure feature get config-key
#  command: cortx_setup config get --key <config-key>

#- name: Configure feature set config-key
#  command: cortx_setup config set --key <config-key> --val <config-value>

