- name: Configure hostname
  shell: cortx_setup node prepare network --hostname $(hostname -f)
 
- name: Node1 Static Config
  shell: cortx_setup node prepare network --type {{item}} --ip_address {{ ip_add_node1 }} --netmask {{ netmask_node1 }} --gateway {{ gateway_node1 }}
  delegate_to: "srvnode-1" 
  loop: 
    - management
    - data
    - private
  
- name: Node2 Static Config
  shell: cortx_setup node prepare network --type {{item}} --ip_address {{ ip_add_node2 }} --netmask {{ netmask_node2 }} --gateway {{ gateway_node2 }}
  delegate_to: "srvnode-2"
  loop: 
    - management
    - data
    - private

- name: Node2 Static Config
  shell: cortx_setup node prepare network --type {{item}} --ip_address {{ ip_add_node3 }} --netmask {{ netmask_node3 }} --gateway {{ gateway_node3 }}
  delegate_to: "srvnode-3"
  loop: 
    - management
    - data
    - private
    
- name: Copy firewall config
  copy:
    src: ~/firewall_config.yaml   
    dest: /root 
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
   
- name: Firewall configuration
  shell: cortx_setup node prepare firewall --config yaml:///root/firewall_config.yaml
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
  
- name: Set the time by providing the NTP server and time zone
  shell: cortx_setup node prepare time --server time.seagate.com --timezone UTC
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
  
- name: Finalize the node
  shell: cortx_setup node prepare finalize
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
  
 

  
