- name: "[prepare] : Install tools [expect] on localhost"
  shell: yum install -y expect
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}"

- name: Display hostname of srvnode1
  shell: echo `hostname`
  delegate_to: "srvnode-1" 
  register: primary_hostname
  
- name: Display hostname of srvnode2
  shell: echo `hostname`
  delegate_to: "srvnode-2" 
  register: secondary_hostname1

- name: Display hostname of srvnode3
  shell: echo `hostname`
  delegate_to: "srvnode-3" 
  register: secondary_hostname2
  
- set_fact:
    primary_host: "{{ primary_hostname.stdout }}"

- set_fact:
    secondary_host1: "{{ secondary_hostname1.stdout }}"
    
- set_fact:
    secondary_host2: "{{ secondary_hostname2.stdout }}"

- name: Cluster Create
  shell: cortx_setup cluster create {{ primary_host }} {{ secondary_host1 }} {{ secondary_host2 }} --name cortx_cluster --site_count 1 --storageset_count 1
  environment:
    CORTX_RELEASE_REPO: "{{ CORTX_BUILD_URL }}"
  delegate_to: srvnode-1
  
#- name: Cluster Create
#  shell: |
#    cortx_setup cluster create {{ primary_host }} {{ secondary_host1 }} {{ secondary_host2 }} --name cortx_cluster --site_count 1 --storageset_count 1

#    expect "Password:"
#    send "{{ host_password }}\n"

#    expect "Password:"
#    send "{{ host_password }}\n"

#    expect "Password:"
#    send "{{ host_password }}\n"
    
 # args:
 #   executable: /usr/bin/expect
 # environment:
 #   CORTX_RELEASE_REPO: "{{ CORTX_BUILD_URL }}"
 # delegate_to: srvnode-1
  
- name: Add network details
  shell: cortx_setup cluster config network --virtual_host {{ MGMT_VIP }}
  environment:
    CORTX_RELEASE_REPO: "{{ CORTX_BUILD_URL }}"
  delegate_to: "srvnode-1"
