- name: Display hostname of srvnode1
  shell: echo `hostname`
  register: primary_hostname
  delegate_to: "srvnode-1"
  
- name: Display hostname of srvnode2
  shell: echo `hostname`
  register: secondary_hostname1
  delegate_to: "srvnode-2"

- name: Display hostname of srvnode3
  shell: echo `hostname`
  register: secondary_hostname2
  delegate_to: "srvnode-3"
  
- set_fact:
    primary_host: "{{ primary_hostname.stdout }}"

- set_fact:
    secondary_host1: "{{ secondary_hostname1.stdout }}"
    
- set_fact:
    secondary_host2: "{{ secondary_hostname2.stdout }}"

- name: Cluster Create
  shell: |
    cortx_setup cluster create {{ primary_host }} {{ secondary_host1 }} {{ secondary_host2 }} --name cortx_cluster --site_count 1 --storageset_count 1

    expect "Password:"
    send "{{ host_password }}\n"

    expect "Password:"
    send "{{ host_password }}\n"

    expect "Password:"
    send "{{ host_password }}\n"
    
  args:
    executable: /usr/bin/expect
  environment:
    CORTX_RELEASE_REPO: "{{ CORTX_BUILD_URL }}"
  delegate_to: srvnode-1
  
- name: Add network details
  shell: cortx_setup cluster config network --virtual_host {{ MGMT_VIP }}
  environment:
    CORTX_RELEASE_REPO: "{{ CORTX_BUILD_URL }}"
  delegate_to: "srvnode-1"
