- name: Cluster definition
  shell: cortx_setup cluster create {{ PRIMARY_HOST }} {{ SECONDARY_HOST1 }} {{ SECONDARY_HOST2 }} --name cortx_cluster --site_count 1 --storageset_count 1
  delegate_to: "srvnode-1"
  
- name: Add network details
  shell: cortx_setup cluster config network --dns_servers {{ DNS_SERVER1 }} {{ DNS_SERVER2 }} --virtual_host {{ MGMT_VIP }} --search_domains {{ SEARCH_DOMAIN1 }} {{ SEARCH_DOMAIN2 }}
  delegate_to: "srvnode-1"
