- name: Prepare cluster
  shell: cortx_setup cluster prepare
  delegate_to: "srvnode-1"
   
- name: Configure cluster
  shell: cortx_setup cluster config
  delegate_to: "srvnode-1"
  
- name: Deploy foundation
  shell: cortx_setup cluster config component --type foundation
 
- name: Deploy IO Path
  shell: cortx_setup cluster config component --type iopath
  
- name: Deploy Control Path
  shell: cortx_setup cluster config component --type controlpath
  
- name: Deploy High Availability Path
  shell: cortx_setup cluster config component --type ha
