- name: Start the cortx cluster
  shell: cortx cluster start
  delegate_to: "srvnode-1"
  
- name: PCS status
  shell: pcs status
  delegate_to: "srvnode-1"
  
- name: HCTL status
  shell: hctl status
  delegate_to: "srvnode-1"
