- include: 01_prepare_environment.yml
  tags: ['01_PREPARE']

- include: 02_factory_manufacturing.yml
  tags: ['02_FACTORY_MANUFACTURING']

- include: 03_security.yml 
  tags: ['03_SECURITY']
  
- include: 04_node_configuration.yml
  tags: ['04_NODE_CONFIGURATION']

