
- name: "[prepare] : Refreshing 'known hosts'"
  command: sed -i "/{{ hostvars['srvnodes'][item]['ansible_host'] }}/d" /root/.ssh/known_hosts
  with_items: "{{ groups['srvnodes'] }}"
  ignore_unreachable: true

- name: "[prepare] : Enable passwordless authentication for ansible->node connection"
  script: files/passwordless_ssh.sh {{ hostvars[item]['ansible_user'] }} {{ hostvars[item]['ansible_host'] }} {{ CLUSTER_PASS }}
  ignore_errors: true
  with_items: "{{ groups['srvnodes'] }}"
  ignore_unreachable: true
