
- name: "[prepare] : Refreshing 'known hosts'"
  command: sed -i "/{{ ansible_host }}/d" /root/.ssh/known_hosts
  delegate_to: localhost
  #with_items: "{{ groups['srvnodes'] }}" 
  ignore_unreachable: true

- name: "[prepare] : Enable passwordless authentication for ansible->node connection"
  script: files/passwordless_ssh.sh {{ ansible_user }} {{ ansible_host }} {{ CLUSTER_PASS }}
  delegate_to: localhost
  ignore_errors: true
  #with_items: "{{ groups['srvnodes'] }}" 
  ignore_unreachable: true
