---
REQUIRED_VARS:
  - HOST
  - CORTX_UTILS_URL
  - CORTX_UTILS_BRANCH
  - THIRD_PARTY_LOCATION
  - CLUSTER_PASS
  - SETUP_TYPE
  - TMPL_CLUSTER_ID
  - TMPL_ROOT_SECRET_KEY

TMPL_BASE_DN: "dc=seagate,dc=com"
TMPL_BIND_BASE_DN: "cn=admin,dc=seagate,dc=com"
TMPL_ROOT_USER: "admin"
TMPL_STORAGE_SET_COUNT: "1"