version: "3"

services:
  eosjenkins-dev:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - "80:8080"
      - "50000:50000"
      - "443:8083"
    volumes:
      - /mnt/jenkins-dev/jenkins.jks:/var/lib/jenkins/jenkins.jks
      - /mnt/jenkins-dev:/var/jenkins_home
      - /mnt/bigstorage/:/mnt/bigstorage
    environment:
      - JAVA_OPTS=-Xmx3072m
      - JENKINS_OPTS= --httpPort=-1 --httpsPort=8083 --httpsKeyStore=/var/lib/jenkins/jenkins.jks --httpsKeyStorePassword=admin123
