---
- name: Revert VM to base snapshot
  hosts: localhost
  gather_facts: false
  become: true
  become_user: root
  roles:
    - role: vm-snapshot-revert
      tags:
        - snapshot-revert

- name: SSH Setup and cortx installation
  hosts: vmware-hosts
  gather_facts: false
  become: true
  become_user: root
  roles:
    - role: vm-ssh-setup
      tags:
        - ssh-setup
    - role: vm-provisioner
      tags:
        - install-cortx

- name: Build OVA file
  hosts: localhost
  gather_facts: false
  become: true
  become_user: root
  roles:
    - role: vm-ovabuild
      tags:
        - ovabuild

- name: Create VM through OVA file  
  hosts: localhost
  gather_facts: false
  become: true
  become_user: root
  roles:
    - role: vm-create
      tags: 
        - create-vm

- name: Test OVA generated VM
  hosts: localhost
  gather_facts: false
  become_user: root
  become: true
  roles:
    - role: ova-tester
      tags:
        - ova-tester
