# Reference : https://github.com/Seagate/cortx-utils/wiki/%22cortx-py-utils%22-single-node-manual-provisioning#utils Mini Provisioning

- name: "[UTILS Mini Provisioning] : Post"
  shell: |
    /opt/ post_install --config yaml:///tmp/utils.post_install.tmpl.1-node
  register: utils_mini_post_install

- name: "[UTILS Mini Provisioning] : Config"
  shell: |
    /opt/ config --config yaml:///tmp/utils.config.tmpl.1-node
  register: utils_mini_config_install

