---

- name: "[reimage] : Re-Image nodes {{ NODE1 }} , {{ NODE2 }} using satellite API" 
  command: python3 -u {{ role_path }}/files/autoreimage.py -p {{ NODE1 }} -s {{ NODE2 }} -un {{ SATELLITE_UN }} -pw {{ SATELLITE_PW }}

- name: "[reimage] : Wait for server to restart"
  wait_for:
      host={{ hostvars[item]['ansible_host'] }}
      port=22
      delay=15
      timeout=1800
  become: false
  ignore_errors: true
  with_items: "{{ groups['nodes'] }}"

- include: change_password.yml
  when: CHANGE_PASS == "yes"
  
- meta: refresh_inventory

- include: passwordless_authentication.yml
