---
- name: "[inband] : Copy scsi RPM package"
  copy:
      src: files/scsi-network-relay-1.1.0-47.x86_64.rpm
      dest: /root/
      owner: root
      group: root
      mode: '0754'
  delegate_to: "{{ item }}"
  with_items: "{{ groups['nodes'] }}"

- name: "[inband] : Create /etc/scsi-network-relay.conf"
  copy:
      src: files/srvnode1
      dest: /etc/scsi-network-relay.conf
      owner: root
      group: root
      mode: '0754'
  delegate_to: "srvnode-1"

- name: "[inband] : Create /etc/scsi-network-relay.conf"
  copy:
      src: files/srvnode2
      dest: /etc/scsi-network-relay.conf
      owner: root
      group: root
      mode: '0754'
  delegate_to: "srvnode-2"

- name: "[inband] : Install scsi RPM package"
  yum: 
    name: /root/scsi-network-relay-1.1.0-47.x86_64.rpm
    state: present
  delegate_to: "{{ item }}"
  with_items: "{{ groups['nodes'] }}"

- name: "[inband] : Start and enable scsi-network-relay service"
  service:
      name: scsi-network-relay
      state: started
  delegate_to: "{{ item }}"
  with_items: "{{ groups['nodes'] }}"

- name: "[inband] : Validate inband by pinging '10.0.0.2', '10.0.0.3'"
  shell: ping -c 1 {{ item.0 }}
  delegate_to: "{{ item.1 }}"
  with_nested:
    - [ '10.0.0.2', '10.0.0.3' ]
    - "{{ groups['nodes'] }}"

