- name: "[password update] : Add host with non root user identity"
  add_host:
    hostname: "{{ item }}"
    groups: tmp_nodes
    ansible_ssh_user: "{{ SERVICE_USER }}"
    ansible_ssh_pass: "{{ SERVICE_PASS }}"
    ansible_become_pass: "{{ SERVICE_PASS }}"
  with_items:
    - "{{ NODE1 }}"
    - "{{ NODE2 }}"

- name: "[password update] : Wait 300 seconds"
  wait_for_connection:
    delay: 60
    timeout: 300

- name: "[password update] : Change root user password on both node"
  user:
    name: root
    update_password: always
    password: "{{ CLUSTER_PASS|password_hash('sha512') }}"
  become: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['tmp_nodes'] }}"
  ignore_unreachable: true
  retries: 3
