---

- name: "[deploy-iso] : Download cortx ISO" 
  get_url:
    url: "{{ BUILD_URL }}"
    dest: "{{ BUILD_URL | basename }}"
    mode: '0755'
  delegate_to: "srvnode-1"
  tags: ['06_DEPLOY']

- name: "[deploy-iso] : Deploy CORTX cluster"
  script: "files/cortx_deploy_iso.sh {{ NODE1 }}  {{ NODE2 }}  {{ CLUSTER_PASS }} {{ BUILD_URL | basename  }}"
  delegate_to: "srvnode-1"
  tags: ['06_DEPLOY']
