- name: "[prepare] : Enable passwordless authentication for ansible->node connection"
  script: files/passwordless_ssh.sh {{ hostvars[item]['ansible_user'] }} {{ hostvars[item]['ansible_host'] }} {{ CLUSTER_PASS }}
  ignore_errors: true
  with_items: "{{ groups['all'] }}"
  ignore_unreachable: True