---

- name: "[Pre-Requisites] : Validate input arguments"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{ REQUIRED_VARS }}"

- name: "[Pre-Requisites] : Setup yum repository"
  template:
    src: cortx.repo.j2
    dest: /etc/yum.repos.d/cortx.repo

- name: "[Pre-Requisites] : Install dependencies"
  shell: yum install -y git gcc jq rpm-build python36 python36-pip python36-devel python36-setuptools openssl-devel libffi-devel python36-dbus

- name: "[Pre-Requisites] : Install py-utils"
  shell: |
    git clone --recursive https://github.com/Seagate/cortx-utils -b main
    cd cortx-utils/py-utils/
    sudo pip3 install -r python_requirements.txt
    sudo pip3 install -r python_requirements.ext.txt
    cd ..
    ./jenkins/build.sh -v 2.0.0 -b 2
    cd py-utils/dist
    yum install -y cortx-py-utils-*.noarch.rpm
    yum install -y symas-openldap symas-openldap-servers symas-openldap-clients openldap-devel python36-ldap

- name: "[Pre-Requisites] : Start slapd service"
  shell: systemctl start slapd

- name: "[Pre-Requisites] : Machine-ID of the VM" 
  shell: cat /etc/machine-id
  register: machineid

- name: "[Pre-Requisites] : FQDN of the VM" 
  shell: hostname
  register: hostname

- set_fact:
    TMPL_HOSTNAME: "{{ hostname.stdout }}"
    TMPL_MACHINE_ID: "{{ machineid.stdout }}"

- name: "[Pre-Requisites] : 8. Update openldap template files" 
  shell:  |
    sed -i "s/TMPL_HOSTNAME/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_MACHINE_ID/{{ TMPL_MACHINE_ID }}/g;  \
        s/TMPL_BASE_DN/{{ TMPL_BASE_DN }}/g; \
        s/TMPL_CLUSTER_ID/{{ TMPL_CLUSTER_ID }}/g; \
        s/TMPL_ROOT_USER/{{ TMPL_ROOT_USER }}/g; \
        s/TMPL_ROOT_SECRET_KEY/{{ TMPL_ROOT_SECRET_KEY }}/g; \
        s/TMPL_STORAGE_SET_COUNT/{{ TMPL_STORAGE_SET_COUNT }}/g; \
        s/TMPL_BIND_BASE_DN/{{ TMPL_BIND_BASE_DN }}/g;" /opt/seagate/cortx/utils/conf/openldap.config.tmpl.1-node
    
    sed -i "s/TMPL_HOSTNAME/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_MACHINE_ID/{{ TMPL_MACHINE_ID }}/g; \
        s/TMPL_BASE_DN/{{ TMPL_BASE_DN }}/g; \
        s/TMPL_CLUSTER_ID/{{ TMPL_CLUSTER_ID }}/g; \
        s/TMPL_ROOT_USER/{{ TMPL_ROOT_USER }}/g; \
        s/TMPL_ROOT_SECRET_KEY/{{ TMPL_ROOT_SECRET_KEY }}/g; \
        s/TMPL_STORAGE_SET_COUNT/{{ TMPL_STORAGE_SET_COUNT }}/g; \
        s/TMPL_BIND_BASE_DN/{{ TMPL_BIND_BASE_DN }}/g;" /opt/seagate/cortx/utils/conf/openldap.init.tmpl.1-node

    sed -i "s/TMPL_HOSTNAME/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_MACHINE_ID/{{ TMPL_MACHINE_ID }}/g;  \
        s/TMPL_BASE_DN/{{ TMPL_BASE_DN }}/g; \
        s/TMPL_CLUSTER_ID/{{ TMPL_CLUSTER_ID }}/g; \
        s/TMPL_ROOT_USER/{{ TMPL_ROOT_USER }}/g; \
        s/TMPL_ROOT_SECRET_KEY/{{ TMPL_ROOT_SECRET_KEY }}/g; \
        s/TMPL_STORAGE_SET_COUNT/{{ TMPL_STORAGE_SET_COUNT }}/g; \
        s/TMPL_BIND_BASE_DN/{{ TMPL_BIND_BASE_DN }}/g;" /opt/seagate/cortx/utils/conf/openldap.test.tmpl.1-node    
