---

- name: "[Pre-Requisites] : Validate input arguments"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{ REQUIRED_VARS }}"

- name: "[Pre-Requisites] : Setup yum repository"
  template:
    src: cortx.repo.j2
    dest: /etc/yum.repos.d/cortx.repo

- name: "[Pre-Requisites] : Install dependencies"
  shell: yum install -y git gcc jq rpm-build python36 python36-pip python36-devel python36-setuptools openssl-devel libffi-devel python36-dbus

- name: "[Pre-Requisites] : Checkout cortx-utils repository"
  git:
    repo: "{{ CORTX_UTILS_URL }}"
    dest: cortx-utils
    version: "{{ CORTX_UTILS_BRANCH }}"

- name: "[Pre-Requisites] : Install python packages"
  shell: |
    pip3 install -r python_requirements.txt
    pip3 install -r python_requirements.ext.txt
  args:
    chdir: cortx-utils/py-utils/

- name: "[Pre-Requisites] : Build py-utils"
  shell: ./jenkins/build.sh -v 2.0.0 -b 2
  args:
    chdir: cortx-utils/   

- name: "[Pre-Requisites] : Install py-utils"
  shell: |
    yum install -y cortx-py-utils-*.noarch.rpm
    yum install -y symas-openldap symas-openldap-servers symas-openldap-clients openldap-devel python36-ldap
  args:
    chdir: cortx-utils/py-utils/dist
       
- name: "[Pre-Requisites] : Start slapd service"
  shell: systemctl start slapd

- name: "[Pre-Requisites] : Machine-ID of the VM" 
  shell: cat /etc/machine-id
  register: machineid
  with_items: "{{ groups['srvnodes'] }}"

- name: "[Pre-Requisites] : FQDN of the VM" 
  shell: hostname
  register: hostname
  with_items: "{{ groups['srvnodes'] }}"

- set_fact:
    TMPL_HOSTNAME: "{{ hostname.stdout }}"
    TMPL_MACHINE_ID: "{{ machineid.stdout }}"
  when: SETUP_TYPE == 'single'

- set_fact:
    TMPL_HOSTNAME1: "{{ hostname.results[0].stdout }}"
    TMPL_MACHINE_ID1: "{{ machineid.results[0].stdout }}"
    TMPL_HOSTNAME2: "{{ hostname.results[1].stdout }}"
    TMPL_MACHINE_ID2: "{{ machineid.results[1].stdout }}"
    TMPL_HOSTNAME3: "{{ hostname.results[2].stdout }}"
    TMPL_MACHINE_ID3: "{{ machineid.results[2].stdout }}"
  when: SETUP_TYPE == '3_node' 

- name: "[Pre-Requisites] : Update single node openldap template files" 
  shell:  |
    sed -i "s/TMPL_HOSTNAME/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_MACHINE_ID/{{ TMPL_MACHINE_ID }}/g;  \
        s/TMPL_BASE_DN/{{ TMPL_BASE_DN }}/g; \
        s/TMPL_CLUSTER_ID/{{ TMPL_CLUSTER_ID }}/g; \
        s/TMPL_ROOT_USER/{{ TMPL_ROOT_USER }}/g; \
        s/TMPL_ROOT_SECRET_KEY/{{ TMPL_ROOT_SECRET_KEY }}/g; \
        s/TMPL_STORAGE_SET_COUNT/{{ TMPL_STORAGE_SET_COUNT }}/g; \
        s/TMPL_BIND_BASE_DN/{{ TMPL_BIND_BASE_DN }}/g;" /opt/seagate/cortx/utils/conf/openldap.config.tmpl.1-node
    
    sed -i "s/TMPL_HOSTNAME/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_MACHINE_ID/{{ TMPL_MACHINE_ID }}/g; \
        s/TMPL_BASE_DN/{{ TMPL_BASE_DN }}/g; \
        s/TMPL_CLUSTER_ID/{{ TMPL_CLUSTER_ID }}/g; \
        s/TMPL_ROOT_USER/{{ TMPL_ROOT_USER }}/g; \
        s/TMPL_ROOT_SECRET_KEY/{{ TMPL_ROOT_SECRET_KEY }}/g; \
        s/TMPL_STORAGE_SET_COUNT/{{ TMPL_STORAGE_SET_COUNT }}/g; \
        s/TMPL_BIND_BASE_DN/{{ TMPL_BIND_BASE_DN }}/g;" /opt/seagate/cortx/utils/conf/openldap.init.tmpl.1-node

    sed -i "s/TMPL_HOSTNAME/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_MACHINE_ID/{{ TMPL_MACHINE_ID }}/g;  \
        s/TMPL_BASE_DN/{{ TMPL_BASE_DN }}/g; \
        s/TMPL_CLUSTER_ID/{{ TMPL_CLUSTER_ID }}/g; \
        s/TMPL_ROOT_USER/{{ TMPL_ROOT_USER }}/g; \
        s/TMPL_ROOT_SECRET_KEY/{{ TMPL_ROOT_SECRET_KEY }}/g; \
        s/TMPL_STORAGE_SET_COUNT/{{ TMPL_STORAGE_SET_COUNT }}/g; \
        s/TMPL_BIND_BASE_DN/{{ TMPL_BIND_BASE_DN }}/g;" /opt/seagate/cortx/utils/conf/openldap.test.tmpl.1-node
  when: SETUP_TYPE == 'single'      

- name: "[Pre-Requisites] : Update 3 node openldap template files" 
  shell:  |
    sed -i "s/TMPL_HOSTNAME1/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_HOSTNAME2/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_HOSTNAME3/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_MACHINE_ID1/{{ TMPL_MACHINE_ID }}/g; \
        s/TMPL_MACHINE_ID2/{{ TMPL_MACHINE_ID }}/g; \
        s/TMPL_MACHINE_ID3/{{ TMPL_MACHINE_ID }}/g; \
        s/TMPL_BASE_DN/{{ TMPL_BASE_DN }}/g; \
        s/TMPL_CLUSTER_ID/{{ TMPL_CLUSTER_ID }}/g; \
        s/TMPL_ROOT_USER/{{ TMPL_ROOT_USER }}/g; \
        s/TMPL_ROOT_SECRET_KEY/{{ TMPL_ROOT_SECRET_KEY }}/g; \
        s/TMPL_STORAGE_SET_COUNT/{{ TMPL_STORAGE_SET_COUNT }}/g; \
        s/TMPL_BIND_BASE_DN/{{ TMPL_BIND_BASE_DN }}/g;" /opt/seagate/cortx/utils/conf/openldap.config.tmpl.3-node
    
    sed -i "s/TMPL_HOSTNAME1/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_HOSTNAME2/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_HOSTNAME3/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_MACHINE_ID1/{{ TMPL_MACHINE_ID }}/g; \
        s/TMPL_MACHINE_ID2/{{ TMPL_MACHINE_ID }}/g; \
        s/TMPL_MACHINE_ID3/{{ TMPL_MACHINE_ID }}/g; \
        s/TMPL_BASE_DN/{{ TMPL_BASE_DN }}/g; \
        s/TMPL_CLUSTER_ID/{{ TMPL_CLUSTER_ID }}/g; \
        s/TMPL_ROOT_USER/{{ TMPL_ROOT_USER }}/g; \
        s/TMPL_ROOT_SECRET_KEY/{{ TMPL_ROOT_SECRET_KEY }}/g; \
        s/TMPL_STORAGE_SET_COUNT/{{ TMPL_STORAGE_SET_COUNT }}/g; \
        s/TMPL_BIND_BASE_DN/{{ TMPL_BIND_BASE_DN }}/g;" /opt/seagate/cortx/utils/conf/openldap.init.tmpl.3-node

    sed -i "s/TMPL_HOSTNAME1/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_HOSTNAME2/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_HOSTNAME3/{{ TMPL_HOSTNAME }}/g;  \
        s/TMPL_MACHINE_ID1/{{ TMPL_MACHINE_ID }}/g; \
        s/TMPL_MACHINE_ID2/{{ TMPL_MACHINE_ID }}/g; \
        s/TMPL_MACHINE_ID3/{{ TMPL_MACHINE_ID }}/g; \
        s/TMPL_BASE_DN/{{ TMPL_BASE_DN }}/g; \
        s/TMPL_CLUSTER_ID/{{ TMPL_CLUSTER_ID }}/g; \
        s/TMPL_ROOT_USER/{{ TMPL_ROOT_USER }}/g; \
        s/TMPL_ROOT_SECRET_KEY/{{ TMPL_ROOT_SECRET_KEY }}/g; \
        s/TMPL_STORAGE_SET_COUNT/{{ TMPL_STORAGE_SET_COUNT }}/g; \
        s/TMPL_BIND_BASE_DN/{{ TMPL_BIND_BASE_DN }}/g;" /opt/seagate/cortx/utils/conf/openldap.test.tmpl.3-node
  when: SETUP_TYPE == '3_node'      
