---

- name: "[OpenLDAP Mini Provisioning] : Post_Install" 
  shell: /opt/seagate/cortx/utils/bin/openldap_setup post_install --config "yaml:///opt/seagate/cortx/utils/conf/openldap.post_install.tmpl"
  tags: ['02_MINI_PROV_POST_INSTALL']

- name: "[OpenLDAP Mini Provisioning] : Prepare"
  shell: /opt/seagate/cortx/utils/bin/openldap_setup prepare --config "yaml:///opt/seagate/cortx/utils/conf/openldap.prepare.tmpl"
  tags: ['02_MINI_PROV_PREPARE']

- name: "[OpenLDAP Mini Provisioning] : Config"
  shell: /opt/seagate/cortx/utils/bin/openldap_setup config --config "yaml:///opt/seagate/cortx/utils/conf/openldap.config.tmpl.1-node"
  tags: ['02_MINI_PROV_CONFIG']

- name: "[OpenLDAP Mini Provisioning] : Init"
  shell: /opt/seagate/cortx/utils/bin/openldap_setup init --config "yaml:///opt/seagate/cortx/utils/conf/openldap.init.tmpl.1-node"
  tags: ['02_MINI_PROV_INIT']