
# #######################################################################################
# Description:
#-------------
#         This tasks validates the motr deployment
# Steps:
#--------
#      1. Validate all the deployment services are up and running
#      2. Validate hctl status
#      3. Validate deployment by performing basic i/o
##########################################################################################

# Log all service facts using ansible module ( this will store service info in ansible_facts.services)
- name: "[prepare] : Get service facts"
  service_facts:
  no_log: True

# Wait for services to start
- name: "[validate] : Wait for service to start"
  command: "hctl status"
  register: hctl_status
  until:
    - "'[started]  hax' in hctl_status.stdout"
    - "'[started]  confd' in hctl_status.stdout"
    - "'[started]  ioservice' in hctl_status.stdout"
  retries: 20
  delay: 30

# Check hctl status
- name: "[validate] : hctl status"
  shell: hctl status 2>&1 | tee -a /root/hctl_status.log

# Check hctl status
- name: "[validate] : Run IO Tests"
  script: files/run_io_tests.sh 2>&1 | tee -a /root/test_motr.log
  register: sanity_test_out
  failed_when: '"IO Test : PASSED" not in sanity_test_out.stdout'