preboarding:
  url: "https://10.230.245.19:28100/#/preboarding/welcome"
  username: "Seagate@123"
  password: "admin"
  email: "admin@seagate.com"
 
onboarding:
  url: "https://10.230.245.19:28100/#/preboarding/login"
  username: "Seagate@123"
  password: "admin"
  system: "System"
  dns: "10.237.10.253,10.237.10.254"
  search: "seagate.com"
  ntp: "time.seagate.com"
