- hosts: localhost
  gather_facts: true
  become_user: root
  become: true
  roles:
    - ova-tester

#- name: SSH Setup on VM
#  hosts: ova_vm
#  gather_facts: true
#  become: true
#  become_user: root
#  tasks:
#    - include_role: 
#        name: vm-ssh-setup

