---
- hosts: vmware-hosts
  become: true
  become_user: "root"
  vars_files:
    - group_vars/secrets.yml
  tasks:
  - name: Create ssh direcotry
    file:
      path: "/root/.ssh"
      state: directory
  
  - name: Create authorized keys file
    file:
      path: "/root/.ssh/authorized_keys"
      state: touch
  
  - name: Place public key in authorized keys
    lineinfile:
      path: "/root/.ssh/authorized_keys"
      line: "{{ pubkey }}"
