---
- name: Install dependency packages
  yum:
    name:
      - python-pyvmomi
    state: present

- vmware_deploy_ovf:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: false
    datacenter: "{{ vsphere_datacenter }}"
    cluster: "{{ vsphere_cluster }}"
    datastore: "{{ vsphere_datastore }}"
    name: "{{ ova_vm_name }}"
    ovf: "{{ ova_file_path }}"
