# #######################################################################################
# Description:
#-------------
#         This tasks performs passwordless ssh between deployment node and localhost
##########################################################################################

# Refresh known hosts
- name: "[prepare] : Refreshing 'known hosts'"
  command: sed -i "/{{ hostvars[item]['ansible_host'] }}/d" /root/.ssh/known_hosts
  with_items: "{{ groups['nodes'] }}"
  ignore_unreachable: True

# Execute passwordless ssh script to copy ket to destination host
- name: "[prepare] : Enable passwordless authentication for ansible->node connection"
  script: files/passwordless_ssh.sh {{ hostvars[item]['ansible_user'] }} {{ hostvars[item]['ansible_host'] }} '{{ CLUSTER_PASS }}'
  with_items: "{{ groups['nodes'] }}"
  ignore_unreachable: True
