ORGANIZATION = "Seagate"

# MongoDB
MONGODB_DB_NAME = "github"
MONGODB_GITHUB_REPOSITORIES_COLLECTION_NAME = "github_repo"
MONGODB_GITHUB_METADATA_COLLECTION_NAME = "github_meta"
MONGODB_GITHUB_BRANCHES_COLLECTION_NAME = "github_branches"
MONGODB_GITHUB_CONTRIBUTORS_COLLECTION_NAME = "github_contributors"
MONGODB_PORT = 27017

# Logstash
GITHUB_REPOSITORY_INDEX_IDENTIFIER = "github_repo"
GITHUB_METADATA_INDEX_IDENTIFIER = "github_meta"
GITHUB_BRANCHES_INDEX_IDENTIFIER = "github_branches"
GITHUB_CONTRIBUTORS_INDEX_IDENTIFIER = "github_contributors"
