
- name: Display hostname of srvnode1
  shell: echo `hostname`
  delegate_to: "srvnode-1" 
  register: primary_hostname
  
- name: Display hostname of srvnode2
  shell: echo `hostname`
  delegate_to: "srvnode-2" 
  register: secondary_hostname1

- name: Display hostname of srvnode3
  shell: echo `hostname`
  delegate_to: "srvnode-3" 
  register: secondary_hostname2
  
- set_fact:
    primary_host: "{{ primary_hostname.stdout }}"

- set_fact:
    secondary_host1: "{{ secondary_hostname1.stdout }}"
    
- set_fact:
    secondary_host2: "{{ secondary_hostname2.stdout }}"

- name: Cluster Create
  script: files/cluster_create.sh  "{{ NODEADMIN_USER }}" "{{ primary_host }}" "{{ NODEADMIN_NEW_PASSWORD }}"  "cluster create {{ primary_host }} {{ secondary_host1 }} {{ secondary_host2 }} --name cortx_cluster --site_count 1 --storageset_count 1 --virtual_host  {{ MGMT_VIP }} --target_build {{ CORTX_BUILD_URL }}"
  delegate_to: srvnode-1
  
