
- name: "[prepare]: Refreshing known hosts"
  command: sed -i "/{{ hostvars[item]['ansible_host'] }}/d" /root/.ssh/known_hosts
  with_items: "{{ groups['srvnodes'] }}"
  ignore_unreachable: true

- name: "[prepare] : Enable passwordless authentication for ansible->node connection"
  shell: sshpass -p "{{ CLUSTER_PASS }}" ssh-copy-id -f -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pub "{{ hostvars[item]['ansible_user'] }}"@"{{ hostvars[item]['ansible_host'] }}"
  ignore_errors: true
  with_items: "{{ groups['srvnodes'] }}"
  ignore_unreachable: true
