# Reference : https://github.com/Seagate/cortx-monitor/wiki/Cortx-monitor-single-node-VM-provisioning-manual:-Manual#sspltest

- name: "[ Validate ] : Wait for service to start"
  command: "systemctl status sspl-ll"
  register: sspl_status
  until:
    - "'[started]  sspl-ll' in sspl_status.stdout"
  retries: 20
  delay: 30

- name: "[ Validate ] : SSPL Sanity Test" 
  shell: /opt/seagate/cortx/sspl/bin/sspl_setup test --config "yaml:///opt/seagate/cortx/sspl/conf/sample_global_cortx_config.yaml" --plan sanity
  register: sspl_mini_test

- debug: var=sspl_mini_test
#  failed_when: '"PASS: S3-Sanity test passed" not in s3_mini_test.stdout'
