name: Add PR to Pull Request Review Board

on:
  pull_request:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: "Pull Request Review Board"
          column: "PR raised"
          repo-token: ${{ secrets.TOKEN }}