name: Base Docker Image CI

on:
  push:
    paths: docker/cortx_components/centos/Dockerfile
  workflow_dispatch:  
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set ENV
      run: |
        echo ::set-env name=INPUT_REPOSITORY::$GITHUB_REPOSITORY
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      env:
          DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
          REPO_NAME: ${{ github.event.repository.name }}
      with:
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: docker/cortx_components/centos/Dockerfile 
        # Build Arguments for docker image build. 
        build_args: 'CENTOS_RELEASE=7.7.1908,USER_PASS=root:"$DEFAULT_PASSWORD"'
        path: docker/cortx_components/centos/
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ env.INPUT_REPOSITORY }}
        tags: 7.7.1908
