name: Dispatch event for cortx submodule
on:
  push:
    branches: [ main ]
jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['Seagate/cortx']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: submodule-update-event
