name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file docker/cortx_components/centos/Dockerfile --build-arg CENTOS_RELEASE=7.7.1908--tag centos_eos:$(date +%s)
