name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Build the Docker image
      uses: buildtool/build-action@v1
      with: 
          docker-build-args: '--build-arg USER_PASS="root:$DEFAULT_PASSWORD" --build-arg CENTOS_RELEASE=7.7.1908'
          dockerfile: docker/cortx_components/centos/Dockerfile
      env:
          DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
     
