name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: pushd docker/cortx_components/centos/ && sed -i 's/enabled=1/enabled=0/g' *.repo && docker build . --file Dockerfile --build-arg USER_PASS="root:$DEFAULT_PASSWORD" --build-arg CENTOS_RELEASE=7.7.1908 --tag centos_eos:$(date +%s) && popd
      env:
          DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
     
