name: "PR Title Checker"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: Seagate/pr-title-checker@main
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}